<?php

/**
 * @file
 * WebService Content module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\xtc\XtendedContent\API\Config;

/**
 * Implements hook_help().
 */
function xtc_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.xtc':
      return Config::getHelp('xtc');
  }
}

/**
 * Perform alterations on help page section plugin definitions.
 *
 * Sections for the page at /admin/help are provided by plugins. This hook
 * allows modules to alter the plugin definitions.
 *
 * @param array $info
 *   Array of plugin information exposed by hook page section plugins, altered
 *   by reference.
 *
 * @see \Drupal\help\HelpSectionPluginInterface
 * @see \Drupal\help\Annotation\HelpSection
 * @see \Drupal\help\HelpSectionManager
 */
function xtc_help_section_info_alter(&$info) {
  // Alter the header for the module overviews section.
  $info['hook_help']['header'] = t('XTC Overviews of modules');
}
