<?php

/**
 * @file
 * WebService Content module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use \Drupal\xtc\XtendedContent\API\Config;

/**
 * Implements hook_help().
 */
function xtc_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.xtc':
      $variables = [
        ':xtc' => Url::fromRoute('help.page', ['name' => 'xtc'])->toString(),
      ];

      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The <a href=":xtc">WebService Content</a> module provide features to pull and push indexes between Drupal instance and ElasticeSearch remote servers.', $variables) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<p>' . t('[to be completed]') . '</p>';

      $output .= Config::getFile('xtc_index_help');

      return $output;
  }

}



