site_name: Xtended Content Documentation

repo_url: https://www.drupal.org/project/xtc
site_description: 'Xtended Content provides access to external content from Drupal 8.'
theme: readthedocs

extra_javascript:
  - js/fix_search.js

markdown_extensions:
  - toc:
      permalink: True

pages:
  - Home: 'index.md'
  - Modules:
      - Xtended Content: 'modules/xtc.md'
      - Xtended Content File: 'modules/xtcfile.md'
  - Plugins:
      - Plugins by modules: 'plugins/plugins-by-modules.md'
      - XTC plugins: 'plugins/xtc-plugins.md'
      - XTC Elastica plugins: 'plugins/xtcelastica-plugins.md'
      - XTC File plugins: 'plugins/xtcfile-plugins.md'
      - XTC Guzzle plugins: 'plugins/xtcguzzle-plugins.md'
      - XTC Search plugins: 'plugins/xtcsearch-plugins.md'
